Make the SDK usable from NuGet
Lombiq/Hastlayer-SDK pull request #103
Opened 2023-04-12 17:51 UTC by Piedone

2023-06-23 21:06 UTC, DAud-IcI requested changes

2023-06-23 21:06 UTC, sarahelsaig commented on Docs/WorkingWithHastlayer.md
> +2. You'll need a hardware framework too; currently, there's only one, so also install the latest version of the `Hast.Vitis.HardwareFramework` NuGet package.
Why semicolon instead of period?

2023-06-23 21:06 UTC, sarahelsaig commented on NuGetTest/Directory.Build.props
> +
```suggestion
```
Remove this empty line or add one between lines 7 and 8 too.

2023-06-23 21:06 UTC, sarahelsaig commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
![image](https://github.com/Lombiq/Hastlayer-SDK/assets/4007293/c7006de7-3661-42e5-ae3e-d518fc438963)

2023-06-23 21:06 UTC, sarahelsaig commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +var configuration = new HardwareGenerationConfiguration("Alveo U250");
~Is this too weird?~ `new AlveoU250Driver(timingReportParser: null).DeviceName`
Turn it into a public constant like we already have with `NexysA7Driver.NexysA7`, then it can be used here.

2023-06-23 21:06 UTC, sarahelsaig commented on NuGetTest/Hast.NuGet.Vhdl.Tests/Hast.NuGet.Vhdl.Tests.csproj
> +    <Nullable>enable</Nullable>
I vaguely recall a discussion that we aren't supposed to randomly enable `<Nullable>enable</Nullable>`?

2023-06-23 21:06 UTC, sarahelsaig commented on NuGetTest/Hast.NuGet.Vhdl.Tests/VerificationTests/XilinxSamplesVerificationTests.cs
> +        var configuration = new HardwareGenerationConfiguration("Nexys A7");
Use `NexysA7Driver.NexysA7`.

2023-06-23 21:06 UTC, DAud-IcI commented on NuGetTest/Readme.md
> +This solution serves as a testbed for the Hastlayer NuGet packages. It's also a simple example of how to use Hastlayer in your project: Just check out `Hast.NuGet.Console`!
Make `Hast.NuGet.Console` a link?

2023-06-25 21:39 UTC, Piedone commented on Docs/WorkingWithHastlayer.md
> +2. You'll need a hardware framework too; currently, there's only one, so also install the latest version of the `Hast.Vitis.HardwareFramework` NuGet package.
Pretentiousness.

![image](https://github.com/Lombiq/Hastlayer-SDK/assets/1976647/59c898ef-ea95-4878-aac7-66c7f5915bc1)

2023-06-25 21:40 UTC, Piedone commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
:D (`e` is a conventional parameter name for event args.)

2023-06-25 21:48 UTC, Piedone commented on NuGetTest/Hast.NuGet.Vhdl.Tests/Hast.NuGet.Vhdl.Tests.csproj
> +    <Nullable>enable</Nullable>
Yeah, I remember the discussion but I think the conclusion was that we'll use it in new projects, and at one point enable it globally. [The corresponding issue's](https://github.com/Lombiq/.NET-Analyzers/issues/48) last point hints on this.

2023-07-24 20:17 UTC, DAud-IcI commented on Docs/WorkingWithHastlayer.md
> +2. You'll need a hardware framework too; currently, there's only one, so also install the latest version of the `Hast.Vitis.HardwareFramework` NuGet package.
😢

2023-07-24 20:18 UTC, DAud-IcI commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
So is `x` for the item in Linq extension methods.

2023-07-24 20:20 UTC, DAud-IcI commented on NuGetTest/Hast.NuGet.Vhdl.Tests/Hast.NuGet.Vhdl.Tests.csproj
> +    <Nullable>enable</Nullable>
Well darn, then I will start using it more in new projects! 😈

2023-07-24 21:30 UTC, Piedone commented on NuGetTest/Hast.NuGet.Vhdl.Tests/Hast.NuGet.Vhdl.Tests.csproj
> +    <Nullable>enable</Nullable>
![giphy](https://github.com/Lombiq/Hastlayer-SDK/assets/1976647/38b7cb79-4ff4-4d47-b2e9-ca2a25b15bb2)

2023-07-24 21:41 UTC, Piedone commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
Oh boy, do we want to debate this here? :D What do you think would be an appropriate parameter name here?

2023-07-25 08:55 UTC, DAud-IcI commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
Debate? Hell naw! I never had a problem with using the new name of the site formerly known as Twitter as a parameter name for Linq methods either. 🙃 This is not a blocker, I just felt petty about pointing out the inconsistency. What you want to do with this information is up to you. 😁

2023-07-25 08:58 UTC, DAud-IcI commented on NuGetTest/Hast.NuGet.Vhdl.Tests/Hast.NuGet.Vhdl.Tests.csproj
> +    <Nullable>enable</Nullable>
![giphy](https://github.com/Lombiq/Hastlayer-SDK/assets/4007293/3dd533fc-d615-4f95-98ad-0cd66af69bb6)
(Huh, you post actually animated GIFs in GH comments now? This changes everything!)

2023-07-25 09:38 UTC, merged

2023-07-25 13:42 UTC, Piedone commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
![image](https://github.com/Lombiq/Hastlayer-SDK/assets/1976647/c44b18c8-7a60-4f85-8ed1-82f4207307e4)

2023-07-25 14:11 UTC, sarahelsaig commented on NuGetTest/Hast.NuGet.Console/Program.cs
> +hastlayer.ExecutedOnHardware += (_, e) =>
Saved for future reference.