INFRA-164: Upgrading Ubuntu PR builds to 2024.4 (warp-ubuntu-2404-x64-4x)
Lombiq/Hastlayer-SDK pull request #128
Opened 2024-10-16 13:21 UTC by BenedekFarkas

2024-10-30 21:08 UTC, Piedone requested changes

2024-10-30 21:08 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      machine-types: "['ubuntu-24.04']"
Since this is the default, it's not needed. Same below.

2024-10-31 14:16 UTC, BenedekFarkas commented on .github/workflows/build-and-test.yml
> +      machine-types: "['ubuntu-24.04']"
Yep, these were meant to be reverted, I just didn't comment that here.

2024-10-31 19:16 UTC, Piedone approved these changes

2024-10-31 19:19 UTC, merged