HAST-179: Remote Worker startup bug fix and Daemon rewrite
Lombiq/Hastlayer-SDK pull request #55
Opened 2021-10-18 03:34 UTC by sarahelsaig

HAST-179
- https://github.com/Lombiq/Hastlayer-Core/pull/7

2021-10-19 01:31 UTC, Piedone requested changes

2021-10-19 01:31 UTC, Piedone commented on Hast.Layer/Hastlayer.cs
> +                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
Ez a `reloadOnChange` nem feltétlenül jó. Így az app egy része már új configot használhat, míg egy másik része még a régivel indult el.

2021-10-19 01:31 UTC, Piedone commented on Hast.Layer/Hastlayer.cs
> +        public DisposableContainer<TServiceInterface1, TServiceInterface2> GetServices<TServiceInterface1, TServiceInterface2>()
Ez egy kicsit olyan `Tuple<T1, T2, T123>`-szerű :(.

2021-10-19 01:31 UTC, Piedone commented on .gitignore
> +/global.json
Ez még korábbi probléma, de a Hast.SDK.Client (a `client` branchben) nem buildelhető.

2021-10-20 02:56 UTC, sarahelsaig commented on Hast.Layer/Hastlayer.cs
> +        public DisposableContainer<TServiceInterface1, TServiceInterface2> GetServices<TServiceInterface1, TServiceInterface2>()
Igen. mert olyan. :) Azzal mi a baj?

2021-10-20 20:58 UTC, Piedone commented on Hast.Layer/Hastlayer.cs
> +        public DisposableContainer<TServiceInterface1, TServiceInterface2> GetServices<TServiceInterface1, TServiceInterface2>()
Olyan kicsit izé, hogy felsorolunk 1, 2, n... type paramétert. Mert akkor igazából hol állunk meg? Kettő nem kevés? :D De nincs jobb ötlete (van a helyi resolve, de annak meg más baja van).

2021-10-20 21:02 UTC, sarahelsaig commented on Hast.Layer/Hastlayer.cs
> +        public DisposableContainer<TServiceInterface1, TServiceInterface2> GetServices<TServiceInterface1, TServiceInterface2>()
Amennyi éppen nekünk kell. Ha valaki szeretne többet majd nyit rá issuet. :D
Elvileg elég egy service, mert lehet az az egy lehet az IServiceProvider de ezt kevésbé éreztem hekkesnek.

2021-10-20 21:12 UTC, Piedone commented on Hast.Layer/Hastlayer.cs
> +        public DisposableContainer<TServiceInterface1, TServiceInterface2> GetServices<TServiceInterface1, TServiceInterface2>()
Igen, utóbbit értettem a helyi resolve alatt. OK lesz.

2021-10-22 21:26 UTC, sarahelsaig commented on .gitignore
> +/global.json
Hogy? Nálam buildeli és publisholja is a 18 nappal ezelőtti v1.2-vel tagelt client branchet:
![image](https://user-images.githubusercontent.com/4007293/138524459-a9b3fee0-3535-45d3-976b-ace7c8f35cb8.png)
![image](https://user-images.githubusercontent.com/4007293/138524510-1454c24a-e295-4286-9b02-e800c599f051.png)

(ugyanez az issue/HAST-179 branchen is)

2021-10-24 19:25 UTC, Piedone commented on .gitignore
> +/global.json
Ugyanazt (42eb2fa8259e78d3ce902bd1c739502093c90784) commit próbálom, Hastlayer.SDK.Client.sln, clean utáni build:
![image](https://user-images.githubusercontent.com/1976647/138609538-638da545-f491-4d50-9c72-b7ef8e8db920.png)

2021-10-24 19:56 UTC, sarahelsaig commented on .gitignore
> +/global.json
Hozzáadtam a Hast.Vitis.Abstractions-t a solutionhöz. Most viszont a Hastlayer-Hardware-Framework---Vitis\Hast.Vitis.Abstractions.HardwareFramework.csproj-t hiányolja ami viszont privát repó. Mi legyen?

2021-10-24 20:07 UTC, Piedone commented on .gitignore
> +/global.json
Hupsz, annak public-ban kellett volna lennie, fixeltem.

2021-10-24 20:19 UTC, sarahelsaig commented on .gitignore
> +/global.json
Hozzáadtam azt is, most már jó nálam: https://github.com/Lombiq/Hastlayer-SDK/pull/57

2021-10-24 20:28 UTC, Piedone commented on .gitignore
> +/global.json
Szuper, nálam is. Viszont azt is kérlek itt add hozzá, hogy együtt tudjam release-elni.

2021-10-24 20:39 UTC, sarahelsaig commented on .gitignore
> +/global.json
Hozzáadtam.

2021-10-26 17:57 UTC, Piedone approved these changes

2021-10-26 17:57 UTC, Piedone commented on Samples/Hast.Samples.Consumer/Program.cs
> +            // A little helper for later.
![image](https://user-images.githubusercontent.com/1976647/138934447-25729874-6b7d-420a-8b6e-c89110096cc5.png)

2021-10-27 02:17 UTC, Piedone approved these changes

2021-10-27 12:48 UTC, merged